name: CI
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Node.js with npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      # Install dependencies using npm
      - run: npm install

      # Lint and build
      - run: npm run test && npm run build
